Решение домашнего задания к занятию "Архитектурные паттерны: MVC"
MTShalopay/-IOSint-homeworks pull request #7
Opened 2022-09-06 21:41 UTC by MTShalopay

2022-09-07 05:22 UTC, Konskii requested changes
Почистить закомментированный код, упростить иниты кнопок и textField ну и пройтись по комментам которые оставил. Желательно на их ответить) В пр апрув не поставлю, но в лк будет зачет.

А почему загадка одна и та же на экранах?)

2022-09-07 05:22 UTC, Konskii commented on Navigation/Custom/CustomButton.swift
> +    init(buttonCustomState: UIControl.State, buttonCustomType: UIButton.ButtonType, buttonCustomTag: Int?, buttonCustomBackground: UIColor, buttonCustomSetTitle: String, buttonCustomSetTitleColor: UI
очень большой инициализатор, который в данном задании Вам не нужен. 

Да и в целом кастомные кнопки в приложениях так не делают - обычно в инициализатор передается какой-то стиль(из созданного Вами енама со стилями), а кнопка уже сама конфигурируется.
Сделайте синит меньше, иначе это противоречит принципу KISS

2022-09-07 05:22 UTC, Konskii commented on Navigation/Custom/CustomTexfield.swift
> +    init(placeholder: String?, tag: Int?, borderWidth: CGFloat, borderColor: CGColor, font: UIFont, textColor: UIColor, tintColor: UIColor, autocapitalizationType: UITextAutocapitalizationType, isSec
аналогично - огромный и не нужны инициализатор.

2022-09-07 05:22 UTC, Konskii commented on Navigation/FeedModel.swift
> +    var secretWord: String = "ops"
private

2022-09-07 05:22 UTC, Konskii commented on Navigation/FeedModel.swift
> +        return true
попробуйте упростить))

2022-09-07 05:22 UTC, Konskii commented on Navigation/VC/FeedViewController.swift
> +       let labelCheck = UILabel()
отсутствует один отступ

2022-09-07 05:22 UTC, Konskii commented on Navigation/VC/FeedViewController.swift
> +            guard self.buttonOne.tag == 0 else { return }
для чего нужна эта проверка?

2022-09-07 05:22 UTC, Konskii commented on Navigation/VC/FeedViewController.swift
> +            guard self.buttonTwo.tag == 1 else { return }
и здесь

2022-09-07 05:22 UTC, Konskii commented on Navigation/VC/FeedViewController.swift
> +        checkGuessButton.action = {
а у этой кнопки такой проверки уже нет. почему?

2022-09-07 05:22 UTC, Konskii commented on Navigation/VC/FeedViewController.swift
> +            if let word = self.wordTextField.text {
на guard заменить

2022-09-07 05:22 UTC, Konskii commented on Navigation/VC/LogInViewController.swift
> +//    private lazy var myButton: UIButton = {
закомментированный код

2022-09-08 18:17 UTC, MTShalopay commented on Navigation/VC/LogInViewController.swift
> +//    private lazy var myButton: UIButton = {
Готово

2022-09-08 18:19 UTC, MTShalopay commented on Navigation/VC/FeedViewController.swift
> +            if let word = self.wordTextField.text {
okey

2022-09-08 18:21 UTC, MTShalopay commented on Navigation/VC/FeedViewController.swift
> +            guard self.buttonOne.tag == 0 else { return }
исправил

2022-09-08 18:22 UTC, MTShalopay commented on Navigation/FeedModel.swift
> +    var secretWord: String = "ops"
Готово

2022-09-11 16:16 UTC, MTShalopay commented on Navigation/FeedModel.swift
> +        return true
Готово

2022-09-11 17:12 UTC, MTShalopay commented on Navigation/VC/FeedViewController.swift
> +        checkGuessButton.action = {
проверку тут не делал потому что она как отдельная костюмная кнопка которая не нуждается в проверке tag

2022-09-11 17:13 UTC, MTShalopay commented on Navigation/VC/FeedViewController.swift
> +            guard self.buttonTwo.tag == 1 else { return }
эта проверка нужна чтобы отследить нажатие какой кнопки было выполнено. чтобы потом уже на следующие листы контроллера передавать тот или иной текст для загадки

2022-09-16 12:31 UTC, MTShalopay commented on Navigation/Custom/CustomButton.swift
> +    init(buttonCustomState: UIControl.State, buttonCustomType: UIButton.ButtonType, buttonCustomTag: Int?, buttonCustomBackground: UIColor, buttonCustomSetTitle: String, buttonCustomSetTitleColor: UI
Понял принял исправил

2022-09-16 12:31 UTC, MTShalopay commented on Navigation/Custom/CustomTexfield.swift
> +    init(placeholder: String?, tag: Int?, borderWidth: CGFloat, borderColor: CGColor, font: UIFont, textColor: UIColor, tintColor: UIColor, autocapitalizationType: UITextAutocapitalizationType, isSec
Понял принял исправил

2022-09-16 12:31 UTC, merged